name: Go
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.13' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Open Web Launch ${{ matrix.go }}-${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: cd cmd/openweblaunch && go build -v .
